name: Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging
      reason:
        description: "Reason for manual deployment"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Configure Render deployment
        run: |
          echo "Configuring Render deployment settings..."
          echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
          echo "Setting PORT to 10000 for Render"
          echo "Ensuring health check endpoint is available at /health"
          echo "Using host binding 0.0.0.0 for proper port detection"
          if [[ -n "${{ github.event.inputs.reason }}" ]]; then
            echo "Deployment reason: ${{ github.event.inputs.reason }}"
          fi

      - name: Deploy to Render
        run: |
          echo "Deploying to ${{ github.event.inputs.environment || 'production' }} environment"
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Wait for Render Deployment
        run: |
          echo "Deployment triggered on Render..."
          echo "Check your Render dashboard for deployment status."
          echo "Deployment URL: https://dashboard.render.com/"
          echo "Workflow run by: ${{ github.actor }}"
          echo "Triggered by: ${{ github.event_name }}"
          echo ""
          echo "Render Configuration:"
          echo "- Environment: ${{ github.event.inputs.environment || 'production' }}"
          echo "- Port: 10000"
          echo "- Health Check Path: /health"
          echo "- Host Binding: 0.0.0.0 (for proper port detection)"
          echo "- MongoDB: Using SSL/TLS with certificate verification disabled for troubleshooting"
